# Generated by Django 4.2.1 on 2023-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukmetoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="year",
            field=models.PositiveIntegerField(default=1970),
            preserve_default=False,
        ),
    ]
