# Generated by Django 4.2.1 on 2023-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ukmetoffice", "0002_weather_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather", name="airfrost", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="raindays1mm",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather", name="rainfall", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather", name="sunshine", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather", name="tmax", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather", name="tmean", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather", name="tmin", field=models.FloatField(null=True),
        ),
    ]
